Repository HANIUM-GROWUP/growthmate-be, pull requests merged in 2023-09, with the labels that each got.

#12 게시글 목록 조회, 게시글 상세 조회, 댓글 목록 조회 API 구현
  growthmate-api/build.gradle
  growthmate-api/src/main/java/com/growup/growthmate/auth/security/LoginMemberResolver.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/security/config/SecurityConfig.java
  growthmate-api/src/main/java/com/growup/growthmate/config/QueryDslConfig.java
  growthmate-api/src/main/java/com/growup/growthmate/query/api/CommunityQueryV1Controller.java
  growthmate-api/src/main/java/com/growup/growthmate/query/application/CommunityQueryService.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/CommunityResponseMapper.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/PagingParams.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/request/CommentQueryRequest.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/request/PostDetailRequest.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/request/PostPreviewRequest.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/response/CommentResponse.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/response/PostDetailResponse.java
  growthmate-api/src/main/java/com/growup/growthmate/query/dto/response/PostPreviewResponse.java
  growthmate-api/src/main/java/com/growup/growthmate/query/repository/CommunityQueryDynamicRepository.java
  growthmate-api/src/main/java/com/growup/growthmate/query/repository/CommunityQueryDynamicRepositoryImpl.java
  growthmate-api/src/main/java/com/growup/growthmate/query/repository/CommunityQueryRepository.java
  growthmate-api/src/main/java/com/growup/growthmate/query/repository/projection/CommentProjection.java
  growthmate-api/src/main/java/com/growup/growthmate/query/repository/projection/PostDetailProjection.java
  growthmate-api/src/main/java/com/growup/growthmate/query/repository/projection/PostPreviewProjection.java
  growthmate-api/src/test/java/com/growup/growthmate/fixture/CommunityFixture.java
  growthmate-api/src/test/java/com/growup/growthmate/query/application/CommunityQueryServiceTest.java
  growthmate-api/src/test/resources/community_fixture.sql
  growthmate-common/src/main/java/com/growup/growthmate/LoginMember.java
  growthmate-core/build.gradle
  growthmate-core/src/main/java/com/growup/growthmate/community/CommunityBaseEntity.java
  growthmate-core/src/main/java/com/growup/growthmate/member/exception/MemberException.java
  growthmate-core/src/main/resources/db/migration/V1__init.sql
Labels: api

#15 COMPANY 테이블 수정 사항 반영
  growthmate-api/src/test/resources/community_fixture.sql
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/Company.java
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/CompanyAnalysis.java
  growthmate-core/src/main/resources/db/migration/V2__company-update.sql
Labels: db

#16 Batch 모듈 추가 및 회사 분석 엔티티 수정
  .gitignore
  .gitmodules
  growthmate-api/build.gradle
  growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/PrincipalOAuth2UserService.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/security/authoriization/JwtAuthorizationFilter.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtSupport.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/token/TokenPayload.java
  growthmate-api/src/main/resources/application.yml
  growthmate-api/src/test/java/com/growup/growthmate/auth/token/JwtSupportTest.java
  growthmate-api/src/test/java/com/growup/growthmate/auth/token/JwtTokenProviderTest.java
  growthmate-batch/build.gradle
  growthmate-batch/src/main/java/com/growup/growthmate/GrowthMateBatchApplication.java
  growthmate-batch/src/main/resources/application-local.yml
  growthmate-batch/src/main/resources/application.yml
  growthmate-core/build.gradle
  growthmate-core/src/main/java/com/growup/growthmate/auth/application/AuthService.java
  growthmate-core/src/main/java/com/growup/growthmate/auth/dto/AuthorizationRequest.java
  growthmate-core/src/main/java/com/growup/growthmate/auth/dto/AuthorizationResponse.java
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/CompanyAnalysis.java
  growthmate-core/src/main/resources/db/migration/V2__company-update.sql
  growthmate-core/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
  settings.gradle
Labels: 설정, db

#18 오각형 변수 분석 API
  growthmate-api/build.gradle
  growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
  growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
  growthmate-api/src/main/java/com/growup/growthmate/company/dto/CompanyAnalysisRequest.java
  growthmate-api/src/main/java/com/growup/growthmate/company/dto/CompanyAnalysisResponse.java
  growthmate-api/src/main/java/com/growup/growthmate/company/mapper/CompanyAnalysisMapper.java
  growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyAnalysisRepository.java
  growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyAnalysisRepositoryImpl.java
  growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyRepository.java
  growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
  growthmate-api/src/test/java/com/growup/growthmate/fixture/CompanyFixture.java
  growthmate-api/src/test/resources/company_fixture.sql
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/exception/CompanyException.java
Labels: api

#19 2차 릴리즈
  .gitignore
  .gitmodules
  growthmate-api/build.gradle
  growthmate-api/src/main/java/com/growup/growthmate/auth/security/authentication/PrincipalOAuth2UserService.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/security/authoriization/JwtAuthorizationFilter.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtSupport.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/token/JwtTokenProvider.java
  growthmate-api/src/main/java/com/growup/growthmate/auth/token/TokenPayload.java
  growthmate-api/src/main/java/com/growup/growthmate/company/api/CompanyV1Controller.java
  growthmate-api/src/main/java/com/growup/growthmate/company/application/CompanyService.java
  growthmate-api/src/main/java/com/growup/growthmate/company/dto/CompanyAnalysisRequest.java
  growthmate-api/src/main/java/com/growup/growthmate/company/dto/CompanyAnalysisResponse.java
  growthmate-api/src/main/java/com/growup/growthmate/company/mapper/CompanyAnalysisMapper.java
  growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyAnalysisRepository.java
  growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyAnalysisRepositoryImpl.java
  growthmate-api/src/main/java/com/growup/growthmate/company/repository/CompanyRepository.java
  growthmate-api/src/main/resources/application.yml
  growthmate-api/src/test/java/com/growup/growthmate/auth/token/JwtSupportTest.java
  growthmate-api/src/test/java/com/growup/growthmate/auth/token/JwtTokenProviderTest.java
  growthmate-api/src/test/java/com/growup/growthmate/company/CompanyServiceTest.java
  growthmate-api/src/test/java/com/growup/growthmate/fixture/CompanyFixture.java
  growthmate-api/src/test/resources/community_fixture.sql
  growthmate-api/src/test/resources/company_fixture.sql
  growthmate-batch/build.gradle
  growthmate-batch/src/main/java/com/growup/growthmate/GrowthMateBatchApplication.java
  growthmate-batch/src/main/resources/application-local.yml
  growthmate-batch/src/main/resources/application.yml
  growthmate-core/build.gradle
  growthmate-core/src/main/java/com/growup/growthmate/auth/application/AuthService.java
  growthmate-core/src/main/java/com/growup/growthmate/auth/dto/AuthorizationRequest.java
  growthmate-core/src/main/java/com/growup/growthmate/auth/dto/AuthorizationResponse.java
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/Company.java
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/CompanyAnalysis.java
  growthmate-core/src/main/java/com/growup/growthmate/company/domain/exception/CompanyException.java
  growthmate-core/src/main/resources/db/migration/V2__company-update.sql
  growthmate-core/src/test/java/com/growup/growthmate/auth/application/AuthServiceTest.java
  settings.gradle
Labels: 배포
